### PR TITLE
UI refactoring for Navigation & Homepage

### LINKED ISSUE #117: Refactor Navigation and Homepage components for better UX

### PR DESCRIPTION
**Pull request by anna-knappe**
Closes #117 

<details><summary>Chat logs</summary>

[UX_improvements_Navigation&Homepage.md](https://github.com/AI-Makes-IT/VTP/files/11152017/UX_improvements_Navigation.Homepage.md)
</details>

### CODE REVIEW

**Review by jjuuliak — CHANGES_REQUESTED** [review]
The code won't compile, I get the following errors:

ERROR in ./src/components/Homepage.js 10:0-29
Module not found: Error: Can't resolve './ui/Card' in client\src\components'

ERROR in ./src/components/Homepage.js 11:0-47
Module not found: Error: Can't resolve './ui/PageContainer' in client\src\components'

**Comment by anna-knappe** [comment]
Lol, looks like I forgot to add the components in the commit.

**Review by jjuuliak — APPROVED** [review]
Looks good!

**Comment by Vinsteri** [comment]
Looks amazing. Merging this to master.

**Pull request merged**
